### ISSUE TITLE
Missing release tarball for 1.7.2

### ISSUE THREAD

**Issue by robert-scheck** [prehor/amavisd-milter#17]
Is it intended that there is no release tarball for 1.7.2 at https://github.com/prehor/amavisd-milter/tags? Yes, there is indeed the GitHub autogenerated release tarball, but that means that aclocal/automake/autoconf needs to be run manually, too (the README refers still to 1.7.1, too).

**Comment by prehor** [comment]
README is updated. Thanks for the hint.
