### ISSUE TITLE
remove amavisd-milter.8 on clean

### ISSUE THREAD

**Issue by haraldj** [prehor/amavisd-milter#9]
Hi Petr please remove amavisd-milter.8 on clean so the source stays clean. Thanks Harald

**Comment by prehor** [comment]
Hi @haraldj,

amavisd-milter.8 could be removed with other generated files using:
```
make maintainer-clean
```

**Comment by haraldj** [comment]
> Hi @haraldj,

Hi Petr,

> 
> amavisd-milter.8 could be removed with other generated files using:
> ```
> make maintainer-clean
> ```

Debian normally only does "make clean" when building a package but I found another solution for this issue so you may close it.

Kind regards
Harald Jenny
